# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Set working directory
WORKDIR /app

# Copy package manifest files
COPY package.json pnpm-lock.yaml ./

# Install dependencies without running lifecycle scripts
RUN pnpm install --ignore-scripts

# Install Node.js type definitions to fix build issues
RUN pnpm add -D @types/node

# Install playwright chromium dependency
RUN npx playwright install chromium

# Copy the rest of the application code
COPY . .

# Build the project
RUN pnpm run build

# Set the entrypoint for the MCP server
ENTRYPOINT [ "node", "dist/index.js" ]
